### ISSUE TITLE
How to respond to invalid accessionNumber

### ISSUE THREAD

**Issue by bgeVam** [nroduit/weasis-pacs-connector#11]
This is a feature request.

Let's say I have one study in my PACS with accessionNumber ABC123. The behaviour I want to implement is:

When I call /weasis-pacs-connector/viewer?requestType=STUDY&accessionNumber=ABC123 I want the jnlp to download etc.

When I call **any** other accessionNumber, I do **not** want the jnlp to be downloaded. I want to respond with an HTTP error code, instead of the user opening weasis just to find out that the file does not exist.

What approach to you recommend to achieve this? Which classes to use etc.

**Comment by bgeVam** [comment]
I managed to achieve this calling the "/manifest" servlet [here](https://github.com/bgeVam/weasis-pacs-connector/commit/93222d0c980acfb3fb4320d93fabc1e66beb35b9).

I still hope you suggest a proper way to do this.

**Comment by nroduit** [comment]
This feature already exists but it doesn't work on the master branch.

When requesting the manifest, you get the error:
HTTP Status 404 - Cannot build Manifest [id=121] - java.lang.IllegalStateException: Empty Patient List
message Cannot build Manifest [id=121] - java.lang.IllegalStateException: Empty Patient List
description The requested resource is not available.

Requesting the viewer will open the empty viewer instead of returning an error. This is an issue when you have the [default configuration](https://github.com/nroduit/weasis-pacs-connector/blob/master/src/main/resources/weasis-connector-default.properties)  "accept.noimage=false"

If you have a fix, you can make a pull request. Otherwise I will treat this issue later.

**Comment by bgeVam** [comment]
I do get the error you describe calling /manifest, but not when calling /viewer or /IHEInvokeImageDisplay. What I want to achieve is that the .jnlp file does not download at all if the image does not exist

**Comment by nroduit** [comment]
The property "accept.noimage=false" is only for the manifest. We could add a new property for the viewer but in general the user expect something.

When the manifest cannot build for any reason, the error message is transmit to the viewer by the manifest. When no image has been found is a specific case with a specific behavior.

**Comment by bgeVam** [comment]
>  but in general the user expect something.

I think that is the point. Weasis is built to open links for pictures that already exist (like opening it by clicking the view icon when its integrated in DCM4CHEE).

In my use case, a prepared weasis link is generated from the point where the order is scheduled. The users need to click the link to find out, if the image already exists on DCM4CHEE or not.

**Comment by nroduit** [comment]
I close the issue.
If you want to know if images exist, you should call the manifest.
