### ISSUE TITLE
Connecting Weasis to DICOMCloud

### ISSUE THREAD

**Issue by shelbypereira** [nroduit/weasis-pacs-connector#32]
I am trying to install and configure to run with [DICOMCloud ](https://github.com/DICOMcloud/DICOMcloud)  (to test the WADO implementation with the Weasis viewer).  I have followed the steps in the installation and Configuration settings of the readme and related links:
-JDK 1.8 ,Maven,TOMCAT and WeasisConnector installed 
maven run with : mvn clean package

However I am unable to find the place where I configure the target WADO server.  In my case it should be localhost:44301 which is the default for DICOMcloud 

Do I also need to specify the urls for WADO-RS, QIDO-RS and STOW and/or WADO-uri somewhere
eg WADO-RS=localhost:44301/wado

or is a default being assumed (/wado, /qido ...

Would be really helpful to have a bit more documentation since the Weasis viewer is quite powerful,  the WADO interface then allows it to connect to most PACSes.

**Comment by nroduit** [comment]
The current implementation of weasis-pacs-connector creates a manifest for Weasis either by[ DICOM queries](https://github.com/nroduit/weasis-pacs-connector/blob/master/src/main/resources/dicom-dcm4chee.properties) or directly by [SQL queries](https://github.com/nroduit/weasis-pacs-connector/blob/master/src/main/resources/db-dcm4chee.properties) but not yet by DICOMWeb (QIDO) queries.

The WADO URI is used by Weasis to download images, see this [page ](https://nroduit.github.io/en/basics/customize/integration/)to better understand the workflow.

This XML manifest is built on the server side because DICOM requests are not adapted for the web and therefore cannot be done on the client side. However, with the new DICOMWeb services, this becomes possible. I am currently implementing the QIDO directly in Weasis to allow the construction of the manifest without using weasis-pacs-connector. Like for example:
weasis://$dicom:rs --url "https://image.com/dicomweb" --studyList "1.3.4342.3,1.2432"

DICOMCloud is not a PACS because it does not contain the basic DICOM services and therefore cannot be configured simply with weasis-pacs-connector. Maybe implementation with SQL queries would be possible. Otherwise, you have to wait for the implementation of the QIDO directly in Weasis.

**Comment by nroduit** [comment]
You can try to connect directly Weasis 3.5.4 to DICOMCloud, see this [post](https://groups.google.com/d/msg/dcm4che/PmjxPzXmrzk/xWXedsPYAwAJ).

I haven't tried. Thank you for giving feedback.

**Comment by nroduit** [comment]
The services structure on DCIOMCould has been [fixed](https://github.com/DICOMcloud/DICOMcloud/issues/59), so now it is possible to connect directly to DICOMCloud via the WADO-RS services.

See the [page](https://nroduit.github.io/en/basics/customize/integration/#download-directly-with-dicomweb-restful-services), URL example: 
```
$dicom:rs --url "https://dicomcloud.azurewebsites.net/api" -r "studyUID=1.2.840.113619.2.25.1.1762157631.873231884.123" -r "studyUID=1.3.6.1.4.1.5962.99.1.2280943358.716200484.1363785608958.3.0"
```
